kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-pv-volume-coordinator
  labels:
    type: local
    app: citus-master
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/home/azureuser/coordinatordata"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pv-claim-coordinator
  labels:
    app: citus-master
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
